services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon  # choose closest
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_TUNNEL_URL
        value: https://<your-app-name>.onrender.com
      - key: NODE_ENV
        value: production
